[private]
default:
    just --list

build: (generate 'factorial')

generate STEM: (xml STEM) (json STEM) (yaml STEM) (mermaid STEM) (dot STEM)

[private]
mkbuild:
    mkdir -p _build

[private]
xml STEM: mkbuild
    poplog pop11 +../poplog/monogram.psv {{STEM}}.mg > {{STEM}}.xml

[private]
json STEM: mkbuild
    poetry run python3 xml_to_json.py --input {{STEM}}.xml > _build/{{STEM}}.json

[private]
yaml STEM: mkbuild
    poetry run python3 xml_to_yaml.py --input {{STEM}}.xml > _build/{{STEM}}.yaml

[private]
mermaid STEM: mkbuild
    poetry run python3 xml_to_mermaid.py --input {{STEM}}.xml > _build/{{STEM}}.mermaid

[private]
dot STEM: mkbuild
    poetry run python3 xml_to_dot.py --input {{STEM}}.xml > _build/{{STEM}}.dot
    dot -Tpng _build/{{STEM}}.dot -o _build/{{STEM}}.png
