name: Update version.go on Tag Push

on:
    push:
      tags:
        - "v*"      # Matches tags starting with "v"
      branches:
        - main       # Restricts to tags pushed to the "main" branch

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Ensure full history is available, including tags

      - name: Extract Git Tag
        id: get_tag
        run: |
          echo "TAG=${GITHUB_REF#refs/tags/}"
          echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Update version.go
        run: |
          echo "package lib" > go/monogram/lib/version.go
          echo "const Version = \"${TAG}\"" >> go/monogram/lib/version.go

      - name: Commit Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "actions@github.com"
          git add go/monogram/lib/version.go
          git commit -m "Update version.go to ${TAG}"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
